apiVersion: v1
kind: Template
metadata:
  name: learning-resources
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: learning-resources
    spec:
      envName: ${ENV_NAME}
      title: Learning resources
      deploymentRepo: https://github.com/RedHatInsights/learning-resources
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/learning-resources
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: learningResources
          title: Learning Resources
          href: "/openshift/learning-resources"
        - appId: learningResources
          title: Learning Resources
          href: "/ansible/learning-resources"
        - appId: learningResources
          title: Learning Resources
          href: "/insights/learning-resources"
        - appId: learningResources
          title: Learning Resources
          href: "/edge/learning-resources"
        - appId: learningResources
          title: Learning Resources
          href: "/iam/learning-resources"
      module:
        manifestLocation: /apps/learningResources/fed-mods.json
        modules:
          - id: learningResources
            module: ./RootApp
            routes:
              - pathname: "/openshift/learning-resources"
                props:
                  bundle: openshift
              - pathname: "/ansible/learning-resources"
                props:
                  bundle: ansible
              - pathname: "/insights/learning-resources"
                props:
                  bundle: insights
              - pathname: "/edge/learning-resources"
                props:
                  bundle: edge
              - pathname: "/settings/learning-resources"
                props:
                  bundle: settings
              - pathname: "/iam/learning-resources"
                props:
                  bundle: iam
        moduleID: learning-resources
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/learning-resources
